In [1]:
# Python Imports
from os import listdir
from os.path import isfile, join

#External Imports
import pandas as pd

In [3]:
# Read in *all* split up .csvs
#! Verify path before running
csv_path = 'C:\Code\school\DAT-490-Data\csvs'
data_lst = []

csv_files = [f for f in listdir(csv_path) if isfile(join(csv_path, f))]

for data_file in csv_files:
    this_csv_path = join(csv_path, data_file)
    data_lst.append(pd.read_csv(this_csv_path))

C:\Users\adenr\AppData\Local\Temp\ipykernel_21608\2574088486.py:10: DtypeWarning: Columns (11,13,57,86) have mixed types. Specify dtype option on import or set low_memory=False.
  data_lst.append(pd.read_csv(this_csv_path))
C:\Users\adenr\AppData\Local\Temp\ipykernel_21608\2574088486.py:10: DtypeWarning: Columns (11,13,86,93) have mixed types. Specify dtype option on import or set low_memory=False.
  data_lst.append(pd.read_csv(this_csv_path))
C:\Users\adenr\AppData\Local\Temp\ipykernel_21608\2574088486.py:10: DtypeWarning: Columns (11,13,78,85,86,93) have mixed types. Specify dtype option on import or set low_memory=False.
  data_lst.append(pd.read_csv(this_csv_path))
C:\Users\adenr\AppData\Local\Temp\ipykernel_21608\2574088486.py:10: DtypeWarning: Columns (11,13,86,93) have mixed types. Specify dtype option on import or set low_memory=False.
  data_lst.append(pd.read_csv(this_csv_path))
C:\Users\adenr\AppData\Local\Temp\ipykernel_21608\2574088486.py:10: DtypeWarning: Columns (11,13,78,85,86,93) have mixed types. Specify dtype option on import or set low_memory=False.
  data_lst.append(pd.read_csv(this_csv_path))
C:\Users\adenr\AppData\Local\Temp\ipykernel_21608\2574088486.py:10: DtypeWarning: Columns (11,13,86,93,94) have mixed types. Specify dtype option on import or set low_memory=False.
  data_lst.append(pd.read_csv(this_csv_path))
C:\Users\adenr\AppData\Local\Temp\ipykernel_21608\2574088486.py:10: DtypeWarning: Columns (11,13,86,93) have mixed types. Specify dtype option on import or set low_memory=False.
  data_lst.append(pd.read_csv(this_csv_path))
C:\Users\adenr\AppData\Local\Temp\ipykernel_21608\2574088486.py:10: DtypeWarning: Columns (11,13,86,93) have mixed types. Specify dtype option on import or set low_memory=False.
  data_lst.append(pd.read_csv(this_csv_path))
C:\Users\adenr\AppData\Local\Temp\ipykernel_21608\2574088486.py:10: DtypeWarning: Columns (11,13,85,86,93) have mixed types. Specify dtype option on import or set low_memory=False.
  data_lst.append(pd.read_csv(this_csv_path))
C:\Users\adenr\AppData\Local\Temp\ipykernel_21608\2574088486.py:10: DtypeWarning: Columns (11,13,86,93) have mixed types. Specify dtype option on import or set low_memory=False.
  data_lst.append(pd.read_csv(this_csv_path))
C:\Users\adenr\AppData\Local\Temp\ipykernel_21608\2574088486.py:10: DtypeWarning: Columns (11,13,86,93) have mixed types. Specify dtype option on import or set low_memory=False.
  data_lst.append(pd.read_csv(this_csv_path))
C:\Users\adenr\AppData\Local\Temp\ipykernel_21608\2574088486.py:10: DtypeWarning: Columns (11,13,85,86,93) have mixed types. Specify dtype option on import or set low_memory=False.
  data_lst.append(pd.read_csv(this_csv_path))

In [4]:
assert len(data_lst) == 12

In [10]:
flight_delays_df = pd.concat(data_lst)

In [15]:
print("Length of Flight Delay Data:", len(flight_delays_df))
flight_delays_df.head()

Length of Flight Delay Data: 7024611

,Year,Quarter,Month,DayofMonth,DayOfWeek,FlightDate,Marketing_Airline_Network,Operated_or_Branded_Code_Share_Partners,DOT_ID_Marketing_Airline,IATA_Code_Marketing_Airline,...,Div5Airport,Div5AirportID,Div5AirportSeqID,Div5WheelsOn,Div5TotalGTime,Div5LongestGTime,Div5WheelsOff,Div5TailNum,Duplicate,Unnamed: 119
0,2021,4,11,17,3,2021-11-17,UA,UA_CODESHARE,19977,UA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN
1,2021,4,11,17,3,2021-11-17,UA,UA_CODESHARE,19977,UA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN
2,2021,4,11,17,3,2021-11-17,UA,UA_CODESHARE,19977,UA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN
3,2021,4,11,17,3,2021-11-17,UA,UA_CODESHARE,19977,UA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN
4,2021,4,11,17,3,2021-11-17,UA,UA_CODESHARE,19977,UA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN

In [14]:
ord_flight_delays_df = flight_delays_df.loc[ ( flight_delays_df['Origin'] == 'ORD' ) | ( flight_delays_df['Dest'] == 'ORD' ) ]

In [16]:
print("Length of ORD Data:", len(ord_flight_delays_df))
ord_flight_delays_df.head()

Length of ORD Data: 599725

,Year,Quarter,Month,DayofMonth,DayOfWeek,FlightDate,Marketing_Airline_Network,Operated_or_Branded_Code_Share_Partners,DOT_ID_Marketing_Airline,IATA_Code_Marketing_Airline,...,Div5Airport,Div5AirportID,Div5AirportSeqID,Div5WheelsOn,Div5TotalGTime,Div5LongestGTime,Div5WheelsOff,Div5TailNum,Duplicate,Unnamed: 119
0,2021,4,11,17,3,2021-11-17,UA,UA_CODESHARE,19977,UA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN
1,2021,4,11,17,3,2021-11-17,UA,UA_CODESHARE,19977,UA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN
2,2021,4,11,17,3,2021-11-17,UA,UA_CODESHARE,19977,UA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN
4,2021,4,11,17,3,2021-11-17,UA,UA_CODESHARE,19977,UA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN
5,2021,4,11,17,3,2021-11-17,UA,UA_CODESHARE,19977,UA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN

In [19]:
ord_flight_delays_df.to_csv('../data/ORD_11_21-11-22.csv')